vol_target_annual: 0.11
tau:
  IR_view: 0.15        # fallback BL se IR(view) < 0.15
  sigma_rel: 0.20      # soglia Frobenius relativa su Σ
  delta_rho: 0.15      # max variazione |Δρ_ij|
  beta_CI_width: 0.25  # cap mapping se CI80(β) troppo ampia
  rc_tol: 0.02         # tolleranza ERC per cluster
execution:
  turnover_cap: 0.40
  gross_leverage_cap: 1.75
  TE_max_factor: 0.02
  adv_cap_ratio: 0.05
regime:
  on: 0.65
  off: 0.45
  dwell_days: 20
  cooldown_days: 10
  activate_streak: 3
  deactivate_streak: 3
  weights:
    hmm: 0.5
    volatility: 0.3
    macro: 0.2
  volatility:
    window: 63
    min_duration: 5
    smoothing: 5
  macro:
    inflation_weight: 0.4
    pmi_weight: 0.35
    real_rate_weight: 0.25
    pmi_threshold: 50.0
    real_rate_threshold: 0.0
    smoothing: 3
drift:
  weight_tol: 0.02
  rc_tol: 0.02
