name: ci
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
          pre-commit install
      - name: Lint & Format
        run: |
          ruff check .
          ruff format --check .
          black --check .
      - name: Tests
        run: |
          pytest -q
