name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_PROGRESS_BAR: "off"
  PYTHONWARNINGS: "default"
  FORCE_COLOR: "1"

jobs:
  lint:
    name: Verifiche di stile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            pytest.ini
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Ruff lint
        run: |
          ruff format --check .
          ruff check .
      - name: Black format
        run: black --check .
      - name: Pre-commit hooks
        run: pre-commit run --all-files --show-diff-on-failure

  type-check:
    name: Controlli statici
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            pytest.ini
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Mypy
        run: mypy fair3

  tests:
    name: Test unitari
    runs-on: ${{ matrix.os }}
    needs: type-check
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            pytest.ini
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Pytest
        run: pytest --maxfail=1 --disable-warnings --durations=20

  package:
    name: Build & packaging
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            pytest.ini
      - name: Installa dipendenze di build
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Costruisci artefatti
        run: python -m build
      - name: Verifica pacchetti
        run: twine check dist/*
      - name: Bytecode sanity check
        run: python -m compileall fair3
      - name: Carica dist
        uses: actions/upload-artifact@v4
        with:
          name: fair3-dist
          path: dist
          if-no-files-found: error
